### ISSUE TITLE
Caused by: java.security.InvalidKeyException: Point is not on curve

### ISSUE THREAD

**Issue by YoungKyonYou** [interaso/webpush#26]
hi, I'm currently trying to use your webpush library in my java springboot project
and having hard time figuring out what's the problem.
Try to follow the Readme.md 
my part of the code is down below.
using node server to get the subscription info with same vapid keys and notificationDto has those info.
And got those vapid keys from "web-push generate-vapid-keys --json"
what could be the problem?
I guess the problem is the vapid keys but not sure. 

![image](https://github.com/interaso/webpush/assets/55623317/f897e5ca-2710-4b1e-a273-2b587ad822eb)

```
Caused by: java.security.InvalidKeyException: Point is not on curve
	at jdk.crypto.ec/sun.security.ec.ECDHKeyAgreement.validate(ECDHKeyAgreement.java:200) ~[jdk.crypto.ec:na]
	at jdk.crypto.ec/sun.security.ec.ECDHKeyAgreement.engineDoPhase(ECDHKeyAgreement.java:147) ~[jdk.crypto.ec:na]
	at java.base/javax.crypto.KeyAgreement.doPhase(KeyAgreement.java:581) ~[na:na]
	at com.interaso.webpush.CryptoKt.generateEcdhSharedSecret(Crypto.kt:109) ~[webpush-1.1.0.jar:na]
	at com.interaso.webpush.WebPush.getBody(WebPush.kt:42) ~[webpush-1.1.0.jar:na]
	at com.interaso.webpush.WebPushService.send(WebPushService.kt:69) ~[webpush-1.1.0.jar:na]
	at com.drrr.infra.notifications.kafka.webpush.WebPushConsumer.consume(WebPushConsumer.java:37) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:169) ~[spring-messaging-6.1.0-M4.jar:6.1.0-M4]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:119) ~[spring-messaging-6.1.0-M4.jar:6.1.0-M4]
	at org.springframework.kafka.listener.adapter.HandlerAdapter.invoke(HandlerAdapter.java:56) ~[spring-kafka-3.0.10.jar:3.0.10]
	at org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:375) ~[spring-kafka-3.0.10.jar:3.0.10]
	at org.springframework.kafka.listener.adapter.RecordMessagingMessageListenerAdapter.onMessage(RecordMessagingMessageListenerAdapter.java:92) ~[spring-kafka-3.0.10.jar:3.0.10]
	at org.springframework.kafka.listener.adapter.RecordMessagingMessageListenerAdapter.onMessage(RecordMessagingMessageListenerAdapter.java:53) ~[spring-kafka-3.0.10.jar:3.0.10]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeOnMessage(KafkaMessageListenerContainer.java:2873) ~[spring-kafka-3.0.10.jar:3.0.10]
	... 12 common frames omitted
```
---
I tried getting my vapid keys from, https://vapidkeys.com/
and still doesnt work
![image](https://github.com/interaso/webpush/assets/55623317/495f1194-b49e-4673-8622-cc4df798d5e7)

**Comment by YoungKyonYou** [comment]
I solved it with using Base64.getUrlDecoder().decode(notificationDto.p256dh()); other then notificationDto.p256dh().getBytes()

**Comment by morki** [comment]
Happy to hear you solve it yourself. If you are using this library, can I ask you to give it a github star to make it more discoverable for others?
